import React from "react";

function head() {
    return (
        <>
            <title>Milestones</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta name="description" content="generated by create next app" />
        </>
    );
}

export default head;
